//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sansNom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int IdArticle { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public double prix { get; set; }
        public int quantite { get; set; }
        public int enStock { get; set; }
        public string categorie { get; set; }
        public string photo { get; set; }
    }
}
